name: Publish APIs
on:
  push:
    branches: [ main ]
jobs:
  FTP-Deploy-Action:
    runs-on: ubuntu-latest
    name:  FTP-Deploy-Action
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          server-dir: ${{ secrets.DIRECTORY }}
          